---
- name: "Playing with Ansible"
  hosts: localhost
  connection: local 
  become: true

  tasks:
  - name: stop current running container
    command: docker stop my-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm my-container
    ignore_errors: yes

  - name: create container using simple image
    command: docker run -d --name my-container -p 8085:8080 python-flask-api
